### ISSUE TITLE
[idea] BlendMode option as property of the Shape

### ISSUE THREAD

**Issue by Joshix-1** [tguerin/newton#42]
`BlendMode.srcIn` makes sense with colored images in `ImageShape` or `ImageAssetShape`, but it doesn't really make sense with `CircleShape`. The current setup would require multiple different Newton widgets if one wants to use different kinds of particles (emojis and coloured circles/squares). That's not really ideal.

My idea is to add `Shape.blendMode`. `Particle.computeTransformation` should return the blendMode (I'm unsure whether Shape.computeTransformation should also do that)

**Comment by tguerin** [comment]
This is a good idea, right now I'm working on finishing implementing physics based animation. The PR will be opened soon and will have an impact on the existing API. I'll provide more hooks at the right place so you can achieve this effortlessly through configuration.

**Comment by tguerin** [comment]
The BlendMode is removed from NewtonPainter and moved to shape configuration. Only Image and ImageAsset have blendMode now. Default BlendMode has been switch to modulate and default color to white (main use case is handling opacity).

Thanks for the idea!

Fixed by [b3617ed](https://github.com/tguerin/newton/pull/43/commits/b3617ed28a99f1436f7ee773983f88e014d08817)

**Comment by Joshix-1** [comment]
_BlendedImage stores blendMode and image, but only image gets used in hashCode and operator==, if i interpret that correctly that means if i use the same image twice with different blendModes the second blendMode will get ignored

**Comment by tguerin** [comment]
The hashcode was badly generated, will fix it.

**Comment by tguerin** [comment]
Fixed in [9748daf](https://github.com/tguerin/newton/pull/43/commits/9748daf9bf04d6f2190cb10d86967c9d60bcc417)
